const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  isMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  getStore: (key) => ipcRenderer.invoke('store-get', key),
  setStore: (key, value) => ipcRenderer.invoke('store-set', key, value),
  getAvailableBrowsers: () => ipcRenderer.invoke('get-available-browsers'),
  selectBrowser: (browserKey) => ipcRenderer.invoke('select-browser', browserKey),
  openStream: async (url) => {
    const result = await ipcRenderer.invoke('open-stream', url);
    if (result?.success) await ipcRenderer.invoke('feature-watch-start', url);
    return result;
  },
  reloadStream: () => ipcRenderer.invoke('reload-stream'),
  closeEmbeddedBrowser: async () => {
    const result = await ipcRenderer.invoke('close-embedded-browser');
    await ipcRenderer.invoke('feature-watch-stop');
    return result;
  },
  updateBrowserBounds: (sidebarExpanded) => ipcRenderer.invoke('update-browser-bounds', sidebarExpanded),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  hideBrowser: () => ipcRenderer.invoke('hide-browser'),
  showBrowser: () => ipcRenderer.invoke('show-browser'),
  getChannels: () => ipcRenderer.invoke('get-channels'),
  addChannel: (channel) => ipcRenderer.invoke('add-channel', channel),
  updateChannel: (channel) => ipcRenderer.invoke('update-channel', channel),
  deleteChannel: (channelId) => ipcRenderer.invoke('delete-channel', channelId),
  checkStreams: () => ipcRenderer.invoke('check-streams'),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('set-auto-launch', enabled),
  setStartMinimized: (enabled) => ipcRenderer.invoke('set-start-minimized', enabled),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  getCookieStatus: () => ipcRenderer.invoke('get-cookie-status'),
  onWindowMaximized: (cb) => ipcRenderer.on('window-maximized', (_, v) => cb(v)),
  onFullscreenChanged: (cb) => ipcRenderer.on('fullscreen-changed', (_, v) => cb(v)),
  onChannelsUpdated: (cb) => ipcRenderer.on('channels-updated', (_, v) => cb(v)),
  onOpenStreamFromNotification: (cb) => ipcRenderer.on('open-stream-from-notification', (_, v) => cb(v)),
  features: {
    getSetting: (key) => ipcRenderer.invoke('feature-get-setting', key),
    setSetting: (key, value) => ipcRenderer.invoke('feature-set-setting', key, value),
    getWatchStats: () => ipcRenderer.invoke('feature-watch-stats'),
    getCurrentMedia: () => ipcRenderer.invoke('feature-current-media'),
    openMultiView: (entries) => ipcRenderer.invoke('feature-open-multiview', entries),
    closeMultiView: () => ipcRenderer.invoke('feature-close-multiview'),
    reloadMultiView: () => ipcRenderer.invoke('feature-reload-multiview'),
    resizeMultiView: () => ipcRenderer.invoke('feature-resize-multiview'),
    hideMultiView: () => ipcRenderer.invoke('feature-hide-multiview'),
    showMultiView: () => ipcRenderer.invoke('feature-show-multiview'),
    getMultiViewState: () => ipcRenderer.invoke('feature-multiview-state'),
    cycleMultiViewAudio: () => ipcRenderer.invoke('feature-multiview-cycle-audio'),
    openPip: (url) => ipcRenderer.invoke('feature-open-pip', url),
    closePip: () => ipcRenderer.invoke('feature-close-pip'),
    getPipState: () => ipcRenderer.invoke('feature-pip-state'),
    getDiscordStatus: () => ipcRenderer.invoke('feature-discord-status'),
    getUpdateState: () => ipcRenderer.invoke('feature-update-state'),
    checkUpdate: () => ipcRenderer.invoke('feature-check-update'),
    installUpdate: () => ipcRenderer.invoke('feature-install-update'),
    onMultiViewState: (cb) => ipcRenderer.on('feature-multiview-state', (_, value) => cb(value)),
    onPipState: (cb) => ipcRenderer.on('feature-pip-state', (_, value) => cb(value)),
    onDiscordStatus: (cb) => ipcRenderer.on('feature-discord-status', (_, value) => cb(value)),
    onUpdateState: (cb) => ipcRenderer.on('feature-update-state', (_, value) => cb(value)),
  },
  enhancements: {
    openPreview: (entry, bounds) => ipcRenderer.invoke('enhancement-preview-open', entry, bounds),
    closePreview: () => ipcRenderer.invoke('enhancement-preview-close'),
    openTournament: (entries) => ipcRenderer.invoke('enhancement-tournament-open', entries),
    closeTournament: () => ipcRenderer.invoke('enhancement-tournament-close'),
    hideTournament: () => ipcRenderer.invoke('enhancement-tournament-hide'),
    showTournament: () => ipcRenderer.invoke('enhancement-tournament-show'),
    getTournamentState: () => ipcRenderer.invoke('enhancement-tournament-state'),
    setVolume: (url, volume) => ipcRenderer.invoke('enhancement-set-volume', url, volume),
    getVolumes: (urls) => ipcRenderer.invoke('enhancement-get-volumes', urls),
    getReleaseNotes: () => ipcRenderer.invoke('enhancement-release-notes'),
    getDiscordClientId: () => ipcRenderer.invoke('enhancement-discord-client-id'),
    onTournamentState: (cb) => ipcRenderer.on('enhancement-tournament-state', (_, value) => cb(value)),
  },
});
